services:

  ocelot.apigateway:
    container_name: ocelot.apigateway
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    ports:
      - "8080:8081"
    build:
      context: .
      dockerfile: Modules/APIGaeway/Ocelot.APIGateway/Dockerfile

