services:

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: Modules/APIGaeway/Ocelot.APIGateway/Dockerfile

  his.api:
    image: ${DOCKER_REGISTRY-}hisapi
    build:
      context: .
      dockerfile: HIS.API/Dockerfile


  identity.pl.api:
    image: ${DOCKER_REGISTRY-}identityplapi
    build:
      context: .
      dockerfile: Modules/IdentityModule/Identity.PL.API/Dockerfile

